#!/usr/bin/env bash
# Creates a fake git repo at .dev/fake-repo with a diverse set of staged + unstaged
# changes across multiple folders so Diffdeck has interesting content to render.
# Idempotent: safe to re-run; rebuilds the working tree from scratch each time.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_DIR="$ROOT_DIR/.dev/fake-repo"
MAKE_PNG="$ROOT_DIR/scripts/_make-png.mjs"

# Procedurally generate a yarn.lock with N entries seeded by a version number,
# so two seeds produce two large, fully-different lockfiles for diff testing.
generate_yarn_lock() {
  local out=$1 count=$2 seed=$3
  awk -v count="$count" -v seed="$seed" 'BEGIN {
    print "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY."
    print "# yarn lockfile v1"
    print ""
    families[0]="react"; families[1]="lodash"; families[2]="express"
    families[3]="webpack"; families[4]="typescript"; families[5]="babel"
    families[6]="eslint"; families[7]="rollup"; families[8]="vite"; families[9]="jest"
    for (i = 1; i <= count; i++) {
      name = families[i % 10] "-plugin-" i
      printf "\"%s@^1.%d.0\":\n", name, seed
      printf "  version \"1.%d.%d\"\n", seed, i
      printf "  resolved \"https://registry.yarnpkg.com/%s/-/%s-1.%d.%d.tgz#%032x\"\n", name, name, seed, i, i * seed * 7919
      printf "  integrity sha512-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%d==\n", i * seed
      printf "  dependencies:\n"
      printf "    \"%s-helper\" \"^1.0.0\"\n", name
      print ""
    }
  }' > "$out"
}

rm -rf "$REPO_DIR"
mkdir -p "$REPO_DIR"
cd "$REPO_DIR"

git init -q -b main
git config user.email "dev@diffdeck.local"
git config user.name "diffdeck dev"

# --- Initial commit: baseline files ---
mkdir -p src/components src/utils src/hooks docs

cat > README.md <<'EOF'
# Demo Project

A toy project used to populate Diffdeck's dev fake repo.
EOF

cat > package.json <<'EOF'
{
  "name": "demo",
  "version": "0.1.0",
  "scripts": {
    "build": "echo build"
  }
}
EOF

cat > src/index.ts <<'EOF'
export { Button } from "./components/Button.js";
export { Card } from "./components/Card.js";
export { formatDate } from "./utils/format.js";
EOF

cat > src/components/Button.tsx <<'EOF'
import * as React from "react";

export function Button(props: { label: string }) {
  return <button>{props.label}</button>;
}
EOF

cat > src/components/Card.tsx <<'EOF'
import * as React from "react";

export function Card(props: { title: string }) {
  return <div className="card"><h3>{props.title}</h3></div>;
}
EOF

cat > src/utils/format.ts <<'EOF'
export function formatDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}
EOF

cat > src/utils/parse.ts <<'EOF'
export function parseInteger(value: string): number {
  return Number.parseInt(value, 10);
}
EOF

cat > src/utils/taskSummary.ts <<'EOF'
type Task = { id: string; payload: string };

export function createTaskSummary(tasks: Task[]): string[] {
  const summary: string[] = [];

  summary.push("phase:boot");
  summary.push("checkpoint-07");
  summary.push("checkpoint-08");
  summary.push("checkpoint-09");
  summary.push("checkpoint-10");
  summary.push("checkpoint-11");
  summary.push("checkpoint-12");
  summary.push("checkpoint-13");
  summary.push("checkpoint-14");
  summary.push("checkpoint-15");
  summary.push("checkpoint-16");
  summary.push("checkpoint-17");
  summary.push("checkpoint-18");
  summary.push("checkpoint-19");
  summary.push("checkpoint-20");
  summary.push("checkpoint-21");
  summary.push("checkpoint-22");
  summary.push("checkpoint-23");
  summary.push("checkpoint-24");
  summary.push("checkpoint-25");
  summary.push("checkpoint-26");
  summary.push("checkpoint-27");
  summary.push("checkpoint-28");
  summary.push("checkpoint-29");
  summary.push("checkpoint-30");
  summary.push("checkpoint-31");
  summary.push("checkpoint-32");
  summary.push("checkpoint-33");
  summary.push("phase:mid");
  summary.push("checkpoint-35");
  summary.push("checkpoint-36");
  summary.push("checkpoint-37");
  summary.push("checkpoint-38");
  summary.push("checkpoint-39");
  summary.push("checkpoint-40");
  summary.push("checkpoint-41");
  summary.push("checkpoint-42");
  summary.push("checkpoint-43");
  summary.push("checkpoint-44");
  summary.push("checkpoint-45");
  summary.push("checkpoint-46");
  summary.push("checkpoint-47");
  summary.push("checkpoint-48");
  summary.push("checkpoint-49");
  summary.push("checkpoint-50");
  summary.push("checkpoint-51");
  summary.push("checkpoint-52");
  summary.push("checkpoint-53");
  summary.push("checkpoint-54");
  summary.push("checkpoint-55");
  summary.push("checkpoint-56");
  summary.push("checkpoint-57");
  summary.push("phase:tail");
  summary.push("checkpoint-59");
  summary.push("checkpoint-60");
  summary.push("checkpoint-61");
  summary.push("checkpoint-62");
  summary.push("checkpoint-63");
  summary.push("checkpoint-64");
  summary.push("checkpoint-65");
  summary.push("checkpoint-66");
  summary.push("checkpoint-67");
  summary.push("checkpoint-68");
  summary.push("checkpoint-69");
  summary.push("checkpoint-70");
  summary.push("checkpoint-71");
  summary.push("checkpoint-72");

  return summary;
}
EOF

cat > src/hooks/useToggle.ts <<'EOF'
import { useState } from "react";

export function useToggle(initial = false): [boolean, () => void] {
  const [value, setValue] = useState(initial);
  return [value, () => setValue((v) => !v)];
}
EOF

cat > docs/intro.md <<'EOF'
# Intro

Welcome to the demo docs.
EOF

cat > legacy.txt <<'EOF'
This is an old file that will be deleted.
EOF

# Large lockfile (~3000 entries × 7 lines ≈ 21k lines) — exercises the huge-diff path.
mkdir -p assets
generate_yarn_lock yarn.lock 3000 1

# Binary blob — deterministic so re-runs produce a stable baseline.
printf 'DIFFDECK-BINARY-FIXTURE-v1\n%.0s' {1..64} > assets/blob.bin
printf '\x00\x01\x02\x03\x04\x05\x06\x07' >> assets/blob.bin

# Images: solid PNGs we can mutate to exercise image diffs (modify / delete / add later).
node "$MAKE_PNG" 64 64 220 80 80   > assets/logo.png       # red — will be modified
node "$MAKE_PNG" 32 32 80 200 80   > assets/old-icon.png   # green — will be deleted

git add -A
git commit -q -m "Initial commit"

# --- Staged + unstaged changes for the diff view ---

# Modify across multiple folders so file-selection in the tree is testable.

cat > README.md <<'EOF'
# Demo Project

A toy project used to populate Diffdeck's dev fake repo.

## Changes

- Added Modal component
- Reworked formatting utilities
EOF

cat > src/index.ts <<'EOF'
export { Button } from "./components/Button.js";
export { Card } from "./components/Card.js";
export { Modal } from "./components/Modal.js";
export { formatDate, formatTime } from "./utils/format.js";
export { parseInteger, parseFloatSafe } from "./utils/parse.js";
export { createTaskSummary } from "./utils/taskSummary.js";
export { useToggle } from "./hooks/useToggle.js";
EOF

cat > src/components/Button.tsx <<'EOF'
import * as React from "react";

interface ButtonProps {
  label: string;
  variant?: "primary" | "secondary";
  onClick?: () => void;
}

export function Button({ label, variant = "primary", onClick }: ButtonProps) {
  return (
    <button className={`btn btn-${variant}`} onClick={onClick}>
      {label}
    </button>
  );
}
EOF

cat > src/components/Card.tsx <<'EOF'
import * as React from "react";

interface CardProps {
  title: string;
  subtitle?: string;
  children?: React.ReactNode;
}

export function Card({ title, subtitle, children }: CardProps) {
  return (
    <div className="card">
      <header>
        <h3>{title}</h3>
        {subtitle ? <p className="subtitle">{subtitle}</p> : null}
      </header>
      <div className="card-body">{children}</div>
    </div>
  );
}
EOF

cat > src/components/Modal.tsx <<'EOF'
import * as React from "react";

interface ModalProps {
  open: boolean;
  onClose: () => void;
  children: React.ReactNode;
}

export function Modal({ open, onClose, children }: ModalProps) {
  if (!open) return null;
  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        {children}
      </div>
    </div>
  );
}
EOF

cat > src/utils/format.ts <<'EOF'
export function formatDate(d: Date): string {
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}

export function formatTime(d: Date): string {
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  return `${hh}:${mm}`;
}
EOF

cat > src/utils/parse.ts <<'EOF'
export function parseInteger(value: string): number {
  const parsed = Number.parseInt(value, 10);
  if (Number.isNaN(parsed)) {
    throw new Error(`Not an integer: ${value}`);
  }
  return parsed;
}

export function parseFloatSafe(value: string): number | null {
  const parsed = Number.parseFloat(value);
  return Number.isNaN(parsed) ? null : parsed;
}
EOF

cat > src/utils/taskSummary.ts <<'EOF'
type Task = { id: string; payload: string };

export function createTaskSummary(tasks: Task[]): string[] {
  const summary: string[] = [];

  summary.push("phase:boot-ready");
  summary.push("checkpoint-07");
  summary.push("checkpoint-08");
  summary.push("checkpoint-09");
  summary.push("checkpoint-10");
  summary.push("checkpoint-11");
  summary.push("checkpoint-12");
  summary.push("checkpoint-13");
  summary.push("checkpoint-14");
  summary.push("checkpoint-15");
  summary.push("checkpoint-16");
  summary.push("checkpoint-17");
  summary.push("checkpoint-18");
  summary.push("checkpoint-19");
  summary.push("checkpoint-20");
  summary.push("checkpoint-21");
  summary.push("checkpoint-22");
  summary.push("checkpoint-23");
  summary.push("checkpoint-24");
  summary.push("checkpoint-25");
  summary.push("checkpoint-26");
  summary.push("checkpoint-27");
  summary.push("checkpoint-28");
  summary.push("checkpoint-29");
  summary.push("checkpoint-30");
  summary.push("checkpoint-31");
  summary.push("checkpoint-32");
  summary.push("checkpoint-33");
  summary.push(`phase:mid-${tasks.length}`);
  summary.push("checkpoint-35");
  summary.push("checkpoint-36");
  summary.push("checkpoint-37");
  summary.push("checkpoint-38");
  summary.push("checkpoint-39");
  summary.push("checkpoint-40");
  summary.push("checkpoint-41");
  summary.push("checkpoint-42");
  summary.push("checkpoint-43");
  summary.push("checkpoint-44");
  summary.push("checkpoint-45");
  summary.push("checkpoint-46");
  summary.push("checkpoint-47");
  summary.push("checkpoint-48");
  summary.push("checkpoint-49");
  summary.push("checkpoint-50");
  summary.push("checkpoint-51");
  summary.push("checkpoint-52");
  summary.push("checkpoint-53");
  summary.push("checkpoint-54");
  summary.push("checkpoint-55");
  summary.push("checkpoint-56");
  summary.push("checkpoint-57");
  if (tasks.length > 0) {
    summary.push(`phase:tail-${tasks[0].id}`);
  }
  summary.push("checkpoint-59");
  summary.push("checkpoint-60");
  summary.push("checkpoint-61");
  summary.push("checkpoint-62");
  summary.push("checkpoint-63");
  summary.push("checkpoint-64");
  summary.push("checkpoint-65");
  summary.push("checkpoint-66");
  summary.push("checkpoint-67");
  summary.push("checkpoint-68");
  summary.push("checkpoint-69");
  summary.push("checkpoint-70");
  summary.push("checkpoint-71");
  summary.push("checkpoint-72");

  return summary;
}
EOF

cat > src/hooks/useToggle.ts <<'EOF'
import { useCallback, useState } from "react";

export function useToggle(initial = false): [boolean, () => void, (next: boolean) => void] {
  const [value, setValue] = useState(initial);
  const toggle = useCallback(() => setValue((v) => !v), []);
  return [value, toggle, setValue];
}
EOF

cat > docs/intro.md <<'EOF'
# Intro

Welcome to the demo docs.

This file has been expanded to cover more topics:

- Components
- Hooks
- Utilities
EOF

rm legacy.txt

# Huge text diff: regenerate yarn.lock with a different seed so every entry's
# version + integrity + tarball hash flips. Produces a ~40k-line patch.
generate_yarn_lock yarn.lock 3000 2

# Binary diff: replace the blob with a different deterministic payload.
printf 'DIFFDECK-BINARY-FIXTURE-v2\n%.0s' {1..96} > assets/blob.bin
printf '\xff\xee\xdd\xcc\xbb\xaa\x99\x88' >> assets/blob.bin

# Image diffs: modify logo, delete old-icon, add a new hero image.
node "$MAKE_PNG" 64 64 80 120 220  > assets/logo.png       # red -> blue
rm assets/old-icon.png                                     # deletion
node "$MAKE_PNG" 96 48 240 200 60  > assets/hero.png       # new addition

# Stage some, leave others unstaged so `git diff` (default) shows interesting output.
# `diffdeck` defaults to working-tree diff, so we stage half and edit half.
# Stage the binary + one image so we cover both staged and unstaged binary/image diffs.
git add src/components/Button.tsx src/components/Modal.tsx src/utils/format.ts docs/intro.md \
        assets/blob.bin assets/hero.png

echo "Fake repo ready at $REPO_DIR"
echo "  Staged:   src/components/Button.tsx, src/components/Modal.tsx, src/utils/format.ts, docs/intro.md,"
echo "            assets/blob.bin (binary), assets/hero.png (new image)"
echo "  Unstaged: README.md, src/index.ts, src/components/Card.tsx, src/utils/parse.ts, src/utils/taskSummary.ts,"
echo "            src/hooks/useToggle.ts, legacy.txt (deleted), yarn.lock (~40k-line diff),"
echo "            assets/logo.png (modified image), assets/old-icon.png (deleted image)"
